# Copyright 2017 TEAM PER LA TRASFORMAZIONE DIGITALE
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Questo e' la descrizione delle API che vengono esposte da dati.gov.it.
# Le API sono pubbliche
swagger: '2.0'
info:
  title: Security Manager API
  description: Security Manager API
  version: "BETA"
  termsOfService: http://termofservice
  contact:
    name: team digitale
    url: https://teamdigitale.governo.it
  license:
    name: Creative Commons 4.0 International
    url: http://creativecommons.org/licenses/by/4.0/
host : localhost:9002
#host : security-manager.default.svc.cluster.local:9000
# will be prefixed to all paths
basePath: /security-manager/v1
# array of all schemes that your API supports
schemes:
  - http
  - https
produces:
  - application/json
consumes:
  - application/json
#securityDefinitions:
  #basicAuth:
    #type: basic
    #description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /sftp/init/{user_id}/{path_to_create}:
    get:
      summary: inits sftp folder
      description: |
        It inits the sftp folder for the given user with a specific folder
      tags:
        - sftp
      operationId: sftp
#      security:
#       - basicAuth: []
      parameters:
        - name: user_id
          in: path
          description: the name of the user
          required: true
          type: string
          format: string
        - name: path_to_create
          in: path
          description: the path of the folder to create
          required: true
          type: string
          format: string
      responses:
        200:
          description: the path created
          schema:
            type: string
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  "/token":
    get:
      summary: Get Token
      description: |
        It returns the JWT token
      tags:
        - JWT Token
      operationId: token
      #security:
        #- basicAuth: []
      responses:
        200:
          description: The JWT token
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  "/ipa/user":
    post:
      tags:
        - IPA
      description: Create a user
      operationId: createIPAuser
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        description: User
        required: true
        schema:
          #type: object
          $ref: '#/definitions/IpaUser'
      responses:
        200:
          description: Success
          schema:
            #type: object
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/group":
    post:
      tags:
        - IPA
      description: Create an freeIPA group
      operationId: createIPAgroup
      produces:
      - application/json
      parameters:
      - name: group
        in: body
        description: freeIPA group
        required: true
        schema:
          $ref: '#/definitions/Group'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/group-useradd/{group}":
    put:
      tags:
        - IPA
      description: Add users to a IPA group
      operationId: addUserToIPAgroup
      produces:
      - application/json
      parameters:
      - name: group
        in: path
        description: Group uid
        required: true
        type: string
      - name: users
        in: body
        description: List of users
        required: true
        schema:
         $ref: '#/definitions/UserList'
      responses:
        200:
          description: Success
          schema:
            #type: object
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/group-userdel/{group}":
    put:
      tags:
        - IPA
      description: Delete users from a IPA group
      operationId: delUserToIPAgroup
      produces:
      - application/json
      parameters:
      - name: group
        in: path
        description: Group uid
        required: true
        type: string
      - name: users
        in: body
        description: List of users
        required: true
        schema:
         $ref: '#/definitions/UserList'
      responses:
        200:
          description: Success
          schema:
            #type: object
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/registration/request":
    post:
      tags:
        - IPA
      description: Handle a user registration request
      operationId: registrationrequest
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        description: User
        required: true
        schema:
          #type: object
          $ref: '#/definitions/IpaUser'
      responses:
        200:
          description: Success
          schema:
            #type: object
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/registration/confirm":
    get:
      tags:
        - IPA
      description: Confirm registration
      operationId: registrationconfirm
      produces:
      - application/json
      parameters:
      - name: token
        in: query
        description: Confirmation token
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            #type: object
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/ipa/user/{mail}":
    get:
      tags:
        - IPA
      description: Show user info
      operationId: showipauser
      produces:
      - application/json
      parameters:
      - name: mail
        in: path
        description: User email
        required: true
        type: string
      responses:
        200:
          description: IPA User
          schema:
            type: object
            $ref: '#/definitions/IpaUser'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/daf/organization":
    post:
      tags:
        - DAF
      description: Create a DAF organization
      operationId: createDAForganization
      produces:
      - application/json
      parameters:
      - name: organization
        in: body
        description: Organization
        required: true
        schema:
          $ref: '#/definitions/DafOrg'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/daf/defaultOrg":
    post:
      tags:
        - DAF
      description: Create default DAF organization
      operationId: createDefaultDAForganization
      produces:
      - application/json
      parameters:
      - name: organization
        in: body
        description: Organization
        required: true
        schema:
          $ref: '#/definitions/DafOrg'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/daf/organization/useradd":
    put:
      tags:
        - DAF
      description: Add auser to DAF organization
      operationId: useraddDAForganization
      produces:
      - application/json
      parameters:
      - name: payload
        in: body
        description: Username and groupCn
        required: true
        schema:
          $ref: '#/definitions/UserAndGroup'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
  "/daf/organization/{orgName}":
    delete:
      tags:
        - DAF
      description: delete DAF organization
      operationId: deleteDAForganization
      produces:
      - application/json
      parameters:
      - name: orgName
        in: path
        description: group Cn
        required: true
        type: string
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/Success'
        500:
          description: Error Message
          schema:
            $ref: '#/definitions/Error'
definitions:
  IpaUser:
    type: object
    required:
      - uid
      - givenname
      - sn
      - mail
    properties:
      uid:
        description: user login
        type: string
      givenname:
        description: First name
        type: string
      sn:
        description: Last name
        type: string
      mail:
        type: string
      userpassword:
        type: string
      organizations:
        type: array
        items:
          type: string
      role:
        type: string
  Group:
    type: object
    required:
      - cn
    properties:
      cn:
        description: group cn
        type: string
  UserList:
    type: object
    required:
      - uid
    properties:
      users:
        type: array
        items:
          type: string
  DafOrg:
    type: object
    required:
      - groupCn
      - defaultUserPwd
      - supSetConnectedDbName
    properties:
      groupCn:
        description: group cn
        type: string
      defaultUserPwd:
        type: string
      supSetConnectedDbName:
        description: Superset connected DB name
        type: string
  UserAndGroup:
    type: object
    required:
      - userId
      - groupCn
    properties:
      groupCn:
        description: group cn
        type: string
      userId:
        description: username
        type: string
  Error:
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Success:
    type: object
    properties:
      message:
        type: string
      fields:
        type: string