apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dataportal-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: 20m
spec:
  tls:
  - hosts:
    - dataportal.daf.teamdigitale.it
  rules:
  - host: dataportal.daf.teamdigitale.it
    http:
      paths:
      - path: /
        backend:
          serviceName: publicdata
          servicePort: 5000
